name: Sync File from URL

on:
  schedule:
    - cron: "0 19 * * *" # 每天 UTC 时间 19:00 (实际北京时间 3:00~4:15) 触发一次
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  sync-file:
    runs-on: ubuntu-latest # 使用 Ubuntu 环境执行任务

    steps:
      # Step 1: 检出当前仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4 # 检出代码，注意使用 actions/checkout@v4

      # Step 2: 下载文件并存储到仓库目录
      - name: Download file from URL
        run: |
          curl -o worker.js https://raw.githubusercontent.com/byJoey/cfnew/refs/heads/main/少年你相信光吗

      # Step 3: 比较文件是否发生变化
      - name: Compare files and commit if different
        run: |
          if ! cmp -s "worker.js" "_worker.js"; then
            echo "Files are different, committing changes..."
            mv -f worker.js _worker.js
            git config --global user.name "admin"
            git config --global user.email "admin@noreply.com"
            git add _worker.js
            git commit -m "Update file from URL"
            git push origin main
          else
            rm -rf worker.js
            echo "Files are the same, no changes."
          fi
